FROM postgres:15.4

RUN apt-get update \
    && apt-get install wget -y \
    && apt-get install postgresql-12-postgis-3 -y \
    && apt-get install postgis -y

ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
# COPY ./db.sql /docker-entrypoint-initdb.d/