-- Truncate 'favorite_driver' table
TRUNCATE TABLE favorite_driver CASCADE;
-- Truncate 'report' table
TRUNCATE TABLE report CASCADE;
-- Truncate 'alert' table
TRUNCATE TABLE alert CASCADE;
-- Truncate 'trip_passenger' table
TRUNCATE TABLE trip_passenger CASCADE;
-- Truncate 'trip_station' table
TRUNCATE TABLE trip_station CASCADE;
-- Truncate 'rating' table
TRUNCATE TABLE rating CASCADE;
-- Truncate 'chat_history' table
TRUNCATE TABLE chat_history CASCADE;
-- Truncate 'trip' table
TRUNCATE TABLE trip CASCADE;
-- Truncate 'locations' table
TRUNCATE TABLE locations CASCADE;
-- Truncate 'driver' table
TRUNCATE TABLE driver CASCADE;
-- Truncate 'users' table
TRUNCATE TABLE users CASCADE;